service: cognito-signup # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - cognito-idp:*
        - logs:*
      Resource: "*"
      functions:
  addRole:
    handler: handler.addRole
    memorySize: 128
